#COMANDOS
# los numeros NO se deben cambiar. Si se quiere cambiar el nombre del comando, se puede cambiar.
command:
  1: get      #Comando que asocia el item de la mano del jugador con Chisel. (si no se ponen argumentos se da el mismo efecto)
  2: help     #Comando que explica cómo usar Chisel.
  3: list     #Comando que muestra por chat las diferentes familias y la selección del usuario.
  4: reset    #Comando que desasocia del jugador cualquier item de Chisel.
  5: reload   #Comando que recarga config.yml por si se hacen cambios.
  6: defaultconfig #Comando que elimina el archivo config.yml y lo sustituye por el por defecto. Útil para actualizaciones del plugin.
  
#---------------------------------------------------------------------------
#PERMISOS
#Nombre de permisos para usar comandos:
#   chisel.command       -> caso general, engloba a los de abajo (recomendado)
#   chisel.command.get   -> permiso para usar comando 1
#   chisel.command.help  -> permiso para usar comando 2
#   chisel.command.list  -> permiso para usar comando 3
#   chisel.command.reset -> permiso para usar comando 4

#Nombre de permisos para funcionalidad de chisel:
#   chisel.work          -> caso general, engloba a los de abajo (recomendado)
#   chisel.work.rotate   -> permiso para el modo rotativo
#   chisel.work.fixed    -> permiso para el modo fijo

#Nombre de permisos para debugar:
#   chisel.debug         -> permiso para usar comandos 5 y 6     (en caso de ponerse, solo a gente con acceso a config.yml)

#---------------------------------------------------------------------------
#FAMILYBLOCKS
# numfamilies es el numero de familias, mantener actualizado
# familyname es el nombre del grupo de bloques
# type son las id de los bloques
# data son las metadatas de los bloques (en el mismo orden)
# lore son los nombres de los bloques (en el mismo orden)

# Nota: debe haber el mismo numero de type, data y lore por cada familia
familyblock:
  numfamilies: 14
  1: 
    familyname: Sandstone
    type: 
    - 24
    - 24
    - 24
    - 43
    - 43
    data: 
    - 0
    - 1
    - 2
    - 1
    - 9
    lore:
    - Normal
    - Chiseled
    - Smooth
    - Slab
    - Lisa
  2: 
    familyname: Red Sandstone
    type:
    - 179
    - 179
    - 179
    - 181
    data:
    - 0
    - 1
    - 2
    - 0
    lore:
    - Normal
    - Chiseled
    - Smooth
    - Slab
  3: 
    familyname: Stone Slab
    type:
    - 43
    - 43
    data:
    - 0
    - 8
    lore:
    - Normal
    - Lisa
  4:   
    familyname: Stone Bricks
    type:
    - 98
#   - 98 <-- Mossy! Tiene crafteo desde 1.8: Stonebrick+Vines
    - 98
    - 98
    - 43
    data:
    - 0
#   - 1
    - 2
    - 3
    - 5
    lore:
    - Normal
#   - Mossy
    - Cracked  #Cracked se puede conseguir en horno, pero es algo menor.
    - Chiseled
    - Slab
  5: 
    familyname: Quartz
    type:
    - 155
    - 155
    - 155
    - 155
    - 155
    - 43
    data:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 7
    lore:
    - Normal
    - Chiseled
    - Pilar Up/Down
    - Pilar East/West
    - Pilar North/South
    - Slab
  6:    
    familyname: Oak Log
    type:
    - 17
    - 17
    - 17
    - 17
    data:
    - 0
    - 4
    - 8
    - 12
    lore:
    - Up/Down
    - East/West
    - North/South
    - 6-side
  7:
    familyname: Spruce Log
    type:
    - 17
    - 17
    - 17
    - 17
    data:
    - 1
    - 5
    - 9
    - 13
    lore:
    - Up/Down
    - East/West
    - North/South
    - 6-side
  8:   
    familyname: Birch Log
    type:
    - 17
    - 17
    - 17
    - 17
    data:
    - 2
    - 6
    - 10
    - 14
    lore:
    - Up/Down
    - East/West
    - North/South
    - 6-side   
  9:   
    familyname: Jungle Log
    type:
    - 17
    - 17
    - 17
    - 17
    data:
    - 3
    - 7
    - 11
    - 15
    lore:
    - Up/Down
    - East/West
    - North/South
    - 6-side 
  10: 
    familyname: Acacia Log
    type:
    - 162
    - 162
    - 162
    - 162
    data:
    - 0
    - 4
    - 8
    - 12
    lore:
    - Up/Down
    - East/West
    - North/South
    - 6-side 
  11:   
    familyname: Dark Oak Log
    type:
    - 162
    - 162
    - 162
    - 162
    data:
    - 1
    - 5
    - 9
    - 13
    lore:
    - Up/Down
    - East/West
    - North/South
    - 6-side
  12:
    familyname: Granite
    type:
    - 1
    - 1
    data:
    - 1
    - 2
    lore:
    - Natural
    - Polished
  13:
    familyname: Diorite
    type:
    - 1
    - 1
    data:
    - 3
    - 4
    lore:
    - Natural
    - Polished
  14:
    familyname: Andesite
    type:
    - 1
    - 1
    data:
    - 5
    - 6
    lore:
    - Natural
    - Polished
    
output:
  header: "§6Chisel:§r "
  help:
  - §o§7Help
  - "§o§7Intercambio de bloques por otros equivalentes y/o sin receta de crafteo. Comandos:"
  - §nget
  - §nlist
  - §nreset
  - §o§7Para más información
  - §o§7http://wiki.minecrafters.es/general:tutoriales:chisel
  list:
    header:
    - §l§a[Familia de bloques]  §7->  §f[Bloque seleccionado]
    toRepeat:
    - §o§a%family   §7-   §f%sel
    concrete:
      header:
      - "§o§a%family:"
      toRepeat:
      - "§o- §f%sel"
      chosen:
      - "§o- §e%sel"
      
  whenChiselIsAssigned:
  - §o§7Chisel vinculado a %item.
  whenChiselCantBeAssigned:
  - §o§cChisel no se puede vincular a %item. Asegurate de que lo que tienes en la mano es un item.
  whenChiselIsUnassigned:
  - §o§7Chisel desvinculado de todos los items.
  
  whenModeChangesToFixed:
  - §o§7Modo cambiado a fijo.
  whenModeChangesToRotate:
  - §o§7Modo cambiado a rotativo.
  whenBlockSelectionMade:
  - §o§a%family   §7->   §f%sel
  
  whenHasNoPermision:
  - §o§cNo tienes permiso para usar Chisel
  whenFamilyDoesntExist:
  - "§o§cNo La familia '%family' no existe!"
  
  whenConfigIsReloaded:
  - §6Config refrescada.
  whenConfigDefault:
  - §6Config devuelta al estado original.